### ISSUE TITLE
cmake failed!

### ISSUE THREAD

**Issue by andyyuan78** [redpony/cdec#80]
ubgpu@ubgpu:~/github/cdec/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LibDL: /usr/lib/x86_64-linux-gnu/libdl.so  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   regex
--   filesystem
--   serialization
--   program_options
--   unit_test_framework
--   system
--   thread
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_auto_decoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_easy_encoder in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so
-- Looking for lzma_lzma_preset in /usr/lib/x86_64-linux-gnu/liblzma.so - found
-- Found LibLZMA: /usr/include (found version "5.1.0") 
-- Found PythonInterp: /usr/bin/python2.7 (found suitable version "2.7.6", minimum required is "2.7") 
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find FLEX (missing: FLEX_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.2/Modules/FindFLEX.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  decoder/CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/ubgpu/github/cdec/build/CMakeFiles/CMakeOutput.log"

**Comment by veer66** [comment]
Did you install Flex?

**Comment by andyyuan78** [comment]
great! thanks!

but the new trouble coming:

undefined reference to symbol 'sem_post@@GLIBC_2.2.5', 

I launch a new post.
