### ISSUE TITLE
cdec-decoder.org vs www.cdec-decoder.org

### ISSUE THREAD

**Issue by mjpost** [redpony/cdec#89]
FYI, [cdec-decoder.org](cdec-decoder.org) loads an old wiki that appears abandoned, while [www.cdec-decoder.org](www.cdec-decoder.org) fetches the updated site.

**Comment by lgibelli** [comment]
currently both websites are empty. Is the project abandoned?

**Comment by redpony** [comment]
It shouldn't be, just not well maintained.

**Comment by xlhdh** [comment]
@lgibelli Clicking on the links above result in empty pages. Copy the URL to the address bar should work!

**Comment by goodmami** [comment]
I see spam littering the web-page... random stuff about gaming hardware. Can someone please restore the original content and review the security for the site?
